config/routes.rb
Mongoidblog::Application.routes.draw do

  devise_for :users

  resources :articles do
      resources:comments
  end

  root :to => "articles#index"

end

app/models/admin_user.rb
class AdminUser
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :null => false, :default => ""
  field :encrypted_password, :type => String, :null => false, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Encryptable
  # field :password_salt, :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::MultiParameterAttributes
  field :name
  field :context
  field :published_on, :type => Date

  validates_presence_of :name
  embeds_many :comments
  # referenced_in :author
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::MultiParameterAttributes
  include Mongoid::Ancestry
  has_ancestry


  field :name, :type => String
  field :content, :type => String
  field :published_on, :type => Date
  embedded_in :article, :inverse_of => :comments


  validates :name, :presence=>true
  validates :content, :presence=>true

end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable and :activatable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  validates_uniqueness_of  :email, :case_insensitive =>false
  attr_accessible  :email, :password, :password_confirmation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_filter :authenticate_user!, :except => [:index, :show]
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_filter :authenticate_user!, :except => [:create, :new]
    def new
          @comment = Article.comment.new(:parent_id => params[:parent_id])
    end


    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create!(params[:comment])
        flash[:notice] = "Comment created!"

        respond_to do |format|
            format.html {redirect_to "/article"}
            format.js
        end
    end
    def destroy
        @article = Article.find(params[:article_id])
        logger.debug(@article)
        @article.comments.each do |comment|
            logger.debug(comment)
            @comment = comment if comment.id == params[:id]
        end
        @comment.destroy unless @comment.nil?
        respond_to do |format|
            format.html { redirect_to "/" }
            format.js
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_comment.html.erb
<div class = "message">

    <b><%=@comment.name + " wrote: "%></b>
    <br>
    <%= @comment.content %>
    <% if @comment.published_on.present? %>
        <br>
        <i><%= " on "%><%= @comment.published_on.strftime("%B %d, %Y") %></i>
    <% end %>
    <br>
    <div class="actions">
        <% if user_signed_in? %>
            <%= link_to "delete", article_comment_path(@article, @comment), 
                :confirm => "Are you sure?", 
                :method => :delete 
            %>
        <% end %>
    </div>
</div>
<br>

app/views/articles/_form.html.erb
<%= form_for @article, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
        <%= f.text_area :context, :rows =>10, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :published_on, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :published_on, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                articles_path, :class => 'btn' %>
  </div>
<% end %>

app/views/articles/create.js.erb
/* Insert a notice between the last comment and the comment form */
$("#comment-notice").html('<div class="flash notice"><%= escape_javascript(flash.discard(:notice)) %></div>');

/* Replace the count of comments */
$("#comments_count").html("<%= pluralize(Comment.count, 'Comment') %>");

/* Add the new comment to the bottom of the comments list */
$("#comments").append("<%= escape_javascript(render(@comment)) %>");

/* Highlight the new comment */
$("#comment_<%= @comment.id %>").effect("highlight", {}, 3000);

/* Reset the comment form */
$("#new_comment")[0].reset();

app/views/articles/edit.html.erb
<%- model_class = @article.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<%- model_class = Article.new.class -%>
<div class = "mainTitle">
    <h1><%=t '.title', :default => "Welcome To My Blog" %></h1>
</div>


<% @articles.each do |article| %>
    <br>
    <div class = articleTitle>
        <h2><%= article.name %></h3>
    </div>
    <br>
    <div class = "articleContent">
        <h4><%= article.context %></h4>

        <% if article.published_on.present? %>
            <h4><i><%= " Sas Ponnapalli | "%><%= article.published_on.strftime("%B %d, %Y") %></i></h4>
            <br>
        <% end %>
    </div>
    <div id = "comments">
        <% if article.comments.size == 0 %>
            <h3><%= "No Comments Added ... yet" %></h3>
            <br>
        <% end %>
        <% if article.comments.size > 0 %>
            <div class = articleTitle>
                <h3 id = "comments_count" ><%= pluralize(article.comments.size, 'Comment') %></h3>
            </div>
            <% for comment in article.comments %>
                <div class = "message">

                    <b><%=comment.name + " wrote: "%></b>
                    <br>
                    <%= comment.content %>
                    <% if comment.published_on.present? %>
                        <br>
                        <i><%= " on "%><%= comment.published_on.strftime("%B %d, %Y") %></i>
                    <% end %>
                    <br>
                    <div class="actions">
                        <% if user_signed_in? %>
                            <%= link_to "delete", article_comment_path(article, comment), 
                                :confirm => "Are you sure?", 
                                :method => :delete 
                            %>
                        <% end %>
                        <%= link_to "reply", article_comment_path(article, comment) %>
                    </div>
                </div>
                <br>
            <% end %>
        <% end %>
    </div>
    <div class = articleTitle>
        <h4>Add Comment</h4>
    </div>
    <%= form_for [article, Comment.new], :html => { :class => 'form-horizontal' }, :remote=>true do |f| %>

        <div class = "control-group">
            <%= f.label :name, :class => 'control-label' %> 
            <div class = "controls">
                <%= f.text_field :name, :class =>'text_field'%>
            </div>
        </div>

        <div class = "control-group">
            <%= f.label :comment, :class => 'control-label' %> 
            <div class = "controls">
                <%= f.text_area :content, :rows=>5,:class =>'text_area'%>
            </div>
        </div>

        <div class="control-group">
            <%= f.label :published_on, :class => 'control-label' %>
            <div class="controls">
                <%= f.date_select :published_on, :class => 'text_field' %>
            </div>
        </div>

        <div class = "form-actions">
            <%= f.submit nil, :class => 'btn btn-primary' %>
        </div>

    <% end %>

    <br>

    <% if user_signed_in? %>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
            edit_article_path(article), :class => 'btn btn-mini' 
        %>
        <%= link_to t('.destroy', :default => t("helpers.links.delete")),
            article_path(article),
            :method => :delete,
            :confirm => t('.confirm', :default => 'Are you sure?'),
            :class => 'btn btn-mini btn-danger'
        %>
    <% end %>

<% end %>


<br>
<% if user_signed_in? %>
    <%= link_to t('.new', :default => t("helpers.links.new")),
        new_article_path,
        :class => 'btn btn-primary' 
    %>
<% end %>

app/views/articles/new.html.erb
<%- model_class = @article.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<%- model_class = @article.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:name) %>:</strong><br>
  <%= @article.name %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:context) %>:</strong><br>
  <%= @article.context %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:published_on) %>:</strong><br>
  <%= @article.published_on %>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              articles_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_article_path(@article), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              article_path(@article),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/comments/create.js.erb
/* Insert a notice between the last comment and the comment form */
$("#comment-notice").html('<div class="flash notice"><%= escape_javascript(flash.discard(:notice)) %></div>');

/* Replace the count of comments */
$("#comments_count").html("<%= pluralize(@article.comments.count, 'Comment') %>");

/* Add the new comment to the bottom of the comments list */
$("#comments").append("<%= escape_javascript(render "articles/comment") %>");

/* Highlight the new comment */
$("#comment_<%= @comment.id %>").effect("highlight", {}, 3000);

/* Reset the comment form */
$("#new_comment")[0].reset();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Mongoidblog</title>
        <%= stylesheet_link_tag    "application", :media => "all" %>
        <%= javascript_include_tag "application" %>
        <%= javascript_include_tag  "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" %>
        <%= javascript_include_tag  "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js"%>
        <%= csrf_meta_tags %>
        <script type=”text/javascript”>
            // function create GetXmlHttpObject
        </script>
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="#">Sas's Webpage</a>
                    <div class="nav-collapse">
                        <ul class="nav">
                            <li><%= link_to "Main"%></li>
                            <li><%= link_to "Blog" %></li>
                            <li><%= link_to "Contact" %></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div> 
        <div class= "container">
            <% flash.each do |name, msg| %>
                <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
                    <a class="close" data-dismiss="alert">×</a>
                    <%= msg %>
                </div>
            <% end %>
            <div class = "row">
                <div class = "span10">
                    <div class="hero-unit">
                        <%= yield %>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>